# -*- coding: utf-8 -*-
"""Windowing frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WgL-zkosauu15x1jhNP12YGZauy5ZRuj
"""

import librosa
import pandas as pd
import numpy as np
import librosa.display
import matplotlib.pyplot as plt
from scipy.signal import get_window
import librosa.display

y, sr = librosa.load("signal.wav")
y_shape = y.shape[0]
duration = y_shape/sr
frame_length = 0.5
win_len = (int)((y_shape/duration)*frame_length)

fft_window = librosa.filters.get_window('hann', win_len, fftbins=True)
fft_window = librosa.util.pad_center(fft_window, win_len)
# Pad the window out to win_len size
fft_window = librosa.util.pad_center(fft_window, win_len)
# Reshape so that the window can be broadcast
fft_window = fft_window.reshape((-1, 1))
# Pad the time series so that frames are centered
y = np.pad(y, int(win_len // 2), mode='reflect')
# Window the time series.
y_frames = librosa.util.frame(y, frame_length=win_len, hop_length=win_len)
hann_frame = (y_frames * fft_window).T

np.savetxt("hann_frame.csv", hann_frame, delimiter=",")